apiVersion: v1
kind: ReplicationController
metadata:
  name: filebeat-rc
spec:
  replicas: 1
  selector:
    name: filebeat-pod
  template:
    metadata:
      labels: 
        name: filebeat-pod
    spec:
      containers:
      - name: filebeat
        image: elastic/filebeat:7.6.2  # https://hub.docker.com/r/elastic/filebeat
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-conf
          subPath: filebeat.yml
        - mountPath: /db/data/
          name: filebeat-logs
      restartPolicy: "Always"
      volumes:
      - name: filebeat-logs
        persistentVolumeClaim:
          claimName: mysql-claim
      - name: filebeat-conf
        configMap:
          name: filebeat-conf
