apiVersion: v1
kind: ReplicationController
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    name: loki
  template:
    metadata:
      name: loki
      labels:
        name: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.0.0
        env:  # 规范时区
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - mountPath: /config
          name: data          
      restartPolicy: "Always"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: loki-claim