apiVersion: v1
kind: ReplicationController
metadata:
  name: veryNginx-rc
  labels:
    name: veryNginx-rc
spec:
  replicas: 1
  selector:
    name: veryNginx-pod
  template:
    metadata:
      labels: 
        name: veryNginx-pod
    spec:
      containers:
      - name: veryNginx
        image: camil/verynginx:v0.3.3.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - name: veryNginx-cfg
            mountPath: "/etc/nginx/conf.d"
      restartPolicy: "Always"
      volumes:
        - name: veryNginx-cfg
          persistentVolumeClaim:
            claimName: veryNginx-claim