apiVersion: v1
kind: ReplicationController
metadata:
  name: verynginx-rc
  labels:
    name: verynginx-rc
spec:
  replicas: 1
  selector:
    name: verynginx-pod
  template:
    metadata:
      labels: 
        name: verynginx-pod
    spec:
      containers:
      - name: verynginx
        image: 192.168.1.4:5000/verynginx-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 80
          name: verynginx
        volumeMounts:
        - name: verynginx-cfg
          mountPath: /opt/verynginx/verynginx/configs/
      restartPolicy: "Always"
      volumes:
      - name: verynginx-cfg
        persistentVolumeClaim:
          claimName: verynginx-cfg