#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: nfs-client-provisioner
#---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          # image: quay-mirror.qiniu.com/external_storage/nfs-client-provisioner:latest
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: x.x.x.x
            - name: NFS_PATH
              value: nfs-path
      volumes:
        - name: nfs-client-root
          nfs:
            server: x.x.x.x
            path: nfs-path
