apiVersion: v1
kind: ReplicationController
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    name: postgresql
  template:
    metadata:
      name: postgresql
      labels:
        name: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:12.0-alpine
        env:  # 规范时区
        - name: TZ
          value: Asia/Shanghai
        - name: POSTGRES_USER        #超级用户
          value: gitlab       #默认密码postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB           #默认数据库
          value: gitlab_production
        - name: POSTGRES_INITDB_ARGS
          value: --data-checksums
# POSTGRES_INITDB_WALDIR 修改日志目录的默认在数据目录不改一并挂载
# PGDATA  修改默认数据库目录 默认/var/lib/postgresql/data 
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
        # livenessProbe:
        #   exec:
        #     command:
        #     - pg_isready
        #     - -h
        #     - localhost
        #     - -U
        #     - gitlab_production
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 5
        # readinessProbe:
        #   exec:
        #     command:
        #     - pg_isready
        #     - -h
        #     - localhost
        #     - -U
        #     - gitlab_production
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1
      restartPolicy: "Always"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-claim
