apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-rc
spec:
  replicas: 1
  selector:
    name: kafka-pod
  template:
    metadata:
      labels: 
        name: kafka-pod
    spec:
      hostAliases:
      - ip: "192.168.1.5"
        hostnames:
        - "fuck.kafka"
      containers:
      - name: kafka
        image: 192.168.1.4:5000/liangguohun/kafka:1.0 
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: KAFKA_ADVERTISED_HOST_NAME 
          valueFrom: 
            fieldRef: 
              fieldPath: status.hostIP
        - name: ZOOKEEPER_DATADIR
          value: "/workspace/data"
        ports:
        - name: kafka
          containerPort: 9092
        - name: kafka-out
          containerPort: 9192
        volumeMounts:
        - mountPath: /tmp/kafka-logs 
          name: log-data
        - mountPath: /var/app/config/server.properties 
          name: kafka-conf
          subPath: server.properties
      restartPolicy: "Always"
      volumes:
      - name: log-data
        persistentVolumeClaim:
          claimName: kafka-claim
      - name: kafka-conf
        configMap:
          name: kafka-conf
