apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  type: NodePort
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
      nodePort: 9092
  selector:
    name: kafka-pod 
