apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-exp-rc
spec:
  replicas: 1
  selector:
    name: redis-exp-pod
  template:
    metadata:
      labels: 
        name: redis-exp-pod
    spec:
      containers:
      - name: redis-exp
        image: 192.168.1.4:5000/liangguohun/redis_exporter:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 9121
          name: redis-exp
      restartPolicy: "Always"