apiVersion: v1
kind: Service
metadata:
  name: redis-exp-svc
  labels: 
    name: redis-exp-svc
spec:
  type: NodePort
  ports:
  - port: 9121
    protocol: TCP
    targetPort: redis-exp
    name: redis-exp
    nodePort: 9121
  selector:
    name: redis-exp-pod