apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmq
spec:
  serviceName: "rocketmq"
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq
  template:
    metadata:
     labels:
       app: rocketmq
    spec:
      containers:
      - name: broker
        image: 192.168.1.4:5000/liangguohun/rocketmq:ROCKETMQ_VERSION
        command: ["sh","mqbroker", "-n","192.168.1.4:9876"]
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai        
        ports:
          - containerPort: 10909
            name: rocketmq-b1
          - containerPort: 10911
            name: rocketmq-b2
        volumeMounts:
          - mountPath: /home/rocketmq/store
            name: rocketmq-store
          - mountPath: /home/rocketmq/rocketmq-ROCKETMQ_VERSION/conf/broker.conf
            name: rocketmq-conf
            subPath: broker.conf
          - mountPath: /home/rocketmq/logs
            name: rocketmq-logs
      - name: namesrv
        image: 192.168.1.4:5000/liangguohun/rocketmq:ROCKETMQ_VERSION
        command: ["sh","mqnamesrv"]
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
          - containerPort: 9876
            name: rocketmq
      volumes:
      - name: rocketmq-store
        persistentVolumeClaim:
          claimName: rocketmq-store
      - name: rocketmq-logs
        persistentVolumeClaim:
          claimName: rocketmq-logs
      - name: rocketmq-conf
        configMap:
          name: rocketmq-conf