apiVersion: v1
kind: ReplicationController
metadata:
  name: rocketmq-rc
spec:
  replicas: 1
  selector:
    name: rocketmq-pod
  template:
    metadata:
      labels: 
        name: rocketmq-pod
    spec:
      containers:
      - name: rocketmq
        image: 192.168.1.4:5000/liangguohun/rocketmq_alpine:4.7.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 9876
          name: rocketmq
        - containerPort: 10909
          name: rocketmq-b1
        - containerPort: 10911
          name: rocketmq-b2
        - containerPort: 10912
          name: rocketmq-b3
        volumeMounts:
        - mountPath: /home/rocketmq/
          name: rocketmq-data
      restartPolicy: "Always"
      volumes:
      - name: rocketmq-data
        persistentVolumeClaim:
          claimName: rocketmq-claim