apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels: 
    name: prometheus-svc
spec:
  type: NodePort
  ports:
  - port: 9090
    protocol: TCP
    targetPort: prometheus
    name: prometheus
    nodePort: 9090
  selector:
    name: prometheus-pod