apiVersion: v1
kind: ReplicationController
metadata:
  name: redmine-rc
spec:
  replicas: 1
  selector:
    name: redmine-pod
  template:
    metadata:
      labels: 
        name: redmine-pod
    spec:
      containers:
      - name: redmine
        image: redmine:4.0.4-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: REDMINE_DB_USERNAME
          value: "Hgsredmine"
        - name: REDMINE_DB_PASSWORD
          value: "xyMm..@hg/0k"
        - name: REDMINE_DB_DATABASE # 我这里是使用了外部的数据库原先有的
          value: redmine
        - name: REDMINE_DB_MYSQL
          value: "192.168.1.4"  #value 只能用字符串
        - name: REDMINE_DB_PORT
          value: "31306"
        - name: REDMINE_NO_DB_MIGRATE
          value: "1"
        ports:
        - containerPort: 3000
          name: redmine
        volumeMounts:
        - name: redmine-files
          mountPath: /usr/src/redmine/files
      restartPolicy: "Always"
      volumes:
      - name: redmine-files
        persistentVolumeClaim:
          claimName: redmine-claim