apiVersion: v1
kind: Service
metadata:
  name: redmine-svc
  labels: 
    name: redmine-svc
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: redmine
    name: redmine
    nodePort: 3000
  selector:
    name: redmine-pod