apiVersion: v1
kind: Service
metadata:
  name: redmine-svc
  labels: 
    name: redmine-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: redmine
    nodePort: 30080
  selector:
    name: redmine-pod