apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
  labels: 
    name: gitlab-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: gitlab
    nodePort: 30080
  selector:
    name: gitlab-pod