apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab-rc
  labels:
    name: gitlab-rc
spec:
  replicas: 1
  selector:
    name: gitlab-pod
  template:
    metadata:
      labels: 
        name: gitlab-pod
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:12.3.4-ce.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        # args: 
        #   - --detach
        ports:
        - name: gitlab-ssh
          containerPort: 22
        - name: gitlab-port
          containerPort: 80
        - name: gitlab-https
          containerPort: 443
        volumeMounts:
          - name: gitlab-cfg
            mountPath: "/etc/gitlab"
          - name: gitlab-log
            mountPath: "/var/log/gitlab"
          - name: gitlab-data
            mountPath: "/var/opt/gitlab"
      restartPolicy: "Always"
      volumes:
        - name: gitlab-cfg
          persistentVolumeClaim:
            claimName: gitlab-cfg
        - name: gitlab-log
          persistentVolumeClaim:
            claimName: gitlab-log
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data