apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
  namespace: kube-system
  labels: 
    name: gitlab-svc
spec:
  type: NodePort
  ports:
  - port: 8888
    protocol: TCP
    targetPort: gitlab-port
    name: gitlab-port
    nodePort: 8888
  - port: 2222
    protocol: TCP
    targetPort: gitlab-ssh
    name: gitlab-ssh
    nodePort: 2222
  selector:
    name: gitlab-pod
#kubectl exec -it gitlab-rc-x47p8 /bin/sh -n kube-system(需要加上命名空间指定不然进不去那)