apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab-rc
  namespace: kube-system
  labels:
    name: gitlab-rc
spec:
  replicas: 1
  selector:
    name: gitlab-pod
  template:
    metadata:
      labels: 
        name: gitlab-pod
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:12.3.4-ce.0
        imagePullPolicy: IfNotPresent
        resources:   #QOS级别Burstable  BestEffort < Burstable < Guaranteed
          limits:
            cpu: 4000m # 代表4核
#            memory: 4Gi
          requests:
            cpu: 1000m
#            memory: 4Gi        
        env:
        - name: TZ
          value: Asia/Shanghai
        # args: 
        #   - --detach
        ports:
        - name: gitlab-ssh
          containerPort: 2222
        - name: gitlab-port
          containerPort: 8888
        - name: gitlab-https
          containerPort: 443
        volumeMounts:
          - name: gitlab-cfg
            mountPath: "/etc/gitlab"
          - name: gitlab-log
            mountPath: "/var/log/gitlab"
          - name: gitlab-data
            mountPath: "/var/opt/gitlab"
      restartPolicy: "Always"
      volumes:
        - name: gitlab-cfg
          persistentVolumeClaim:
            claimName: gitlab-cfg
        - name: gitlab-log
          persistentVolumeClaim:
            claimName: gitlab-log
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data