apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
  namespace: kube-system
  labels: 
    name: gitlab-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: gitlab-port
    name: gitlab-port
    nodePort: 8888
  - port: 22
    protocol: TCP
    targetPort: gitlab-ssh
    name: gitlab-ssh
    nodePort: 2222
  selector:
    name: gitlab-pod