apiVersion: v1
kind: ReplicationController
metadata:
  name: rocketmq-exp-rc
spec:
  replicas: 1
  selector:
    name: rocketmq-exp-pod
  template:
    metadata:
      labels: 
        name: rocketmq-exp-pod
    spec:
      containers:
      - name: rocketmq-exp
        image: 192.168.1.4:5000/liangguohun/rocketmq_exporter:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 5557
          name: rocketmq-exp
      restartPolicy: "Always"