apiVersion: v1
kind: Service
metadata:
  name: rocketmq-exp-svc
  labels: 
    name: rocketmq-exp-svc
spec:
  type: NodePort
  ports:
  - port: 5557
    protocol: TCP
    targetPort: rocketmq-exp
    name: rocketmq-exp
    nodePort: 5557
  selector:
    name: rocketmq-exp-pod