apiVersion: v1
kind: ReplicationController
metadata:
  name: runner-rc
  namespace: kube-system
  labels:
    name: runner-rc
spec:
  replicas: 1
  selector:
    name: runner-pod
  template:
    metadata:
      labels: 
        name: runner-pod
    spec:
      containers:
      - name: runner
        # image: 192.168.1.4:5000/min_gitlab-runner:v1.0
        image: gitlab/gitlab-runner:alpine-v12.3.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        # - mountPath: /etc/gitlab-runner/certs
        #   name: ca-crt
      restartPolicy: "Always"
      # volumes:
      # - name: ca-crt
      #   configMap:
      #     name: ca-crt
      #     items:
      #     - key: ca.crt
      #       path: ca.crt
#kubectl exec -it runner-rc-jjvrd /bin/sh -n kube-system(需要加上命名空间指定不然进不去那)
