apiVersion: v1
kind: ReplicationController
metadata:
  name: runner-rc
  labels:
    name: runner-rc
spec:
  replicas: 1
  selector:
    name: runner-pod
  template:
    metadata:
      labels: 
        name: runner-pod
    spec:
      containers:
      - name: runner
        image: 192.168.1.4:5000/min_gitlab-runner:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
      restartPolicy: "Always"