apiVersion: v1
kind: ReplicationController
metadata:
  name: runner-rc
  namespace: kube-system
  labels:
    name: runner-rc
spec:
  replicas: 1
  selector:
    name: runner-pod
  template:
    metadata:
      labels: 
        name: runner-pod
    spec:
      containers:
      - name: runner
        # image: 192.168.1.4:5000/min_gitlab-runner:v1.0
        image: gitlab/gitlab-runner:alpine-v12.3.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
          - mountPath: /etc/gitlab-runner
            name: gitlab-runner
      restartPolicy: "Always"
      volumes:
        - name: gitlab-runner
          persistentVolumeClaim:
            claimName: gitlab-runner
#kubectl exec -it runner-rc-jjvrd /bin/sh -n kube-system(需要加上命名空间指定不然进不去那)
