apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana-rc
spec:
  replicas: 1
  selector:
    name: grafana-pod
  template:
    metadata:
      labels: 
        name: grafana-pod
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:6.7.2-ubuntu  # https://hub.docker.com/_/grafana
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 3000
          name: grafana-port       # 默认管理员账号 admin/admin
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
        - mountPath: /usr/share/grafana/conf
          name: grafana-conf
      restartPolicy: "Always"
      volumes:
      - name: grafana-data
        persistentVolumeClaim: 
          claimName: grafana-data
      - name: grafana-conf
        persistentVolumeClaim: 
          claimName: grafana-conf
