#!/bin/sh

set -e
(
cat <<EOF
{
  "insecure-registries":["192.168.1.4:8443","192.168.1.4:5000"]
}
EOF
) >/etc/docker/daemon.json

systemctl daemon-reload
systemctl restart docker

#"registry-mirrors": ["http://192.168.1.4:8443"],
#docker login 192.168.1.4:5000
#admin/admin123
