kind: Pod
apiVersion: v1
metadata:
  name: nexus3-pod
spec:
  containers:
  - name: nexus3-pod
    image: sonatype/nexus3:3.15.2
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/nexus-data"
    ports:        　　　　　　        #需要暴露的端口库号列表
    - name: nexus3-web      　　　        #端口的名称
      containerPort: 8081                #容器需要监听的端口号
      hostPort: 8081     　　             #容器所在主机需要监听的端口号，默认与Container相同
      protocol: TCP                  #端口协议，支持TCP和UDP，默认TCP
    - name: nexus3-https
      containerPort: 443
    - name: nexus3-docker-regist
      containerPort: 8083
    - name: nexus3-docker-push
      containerPort: 5000
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      nfs: 
        server: 192.168.1.4
        path: /nexus-data
      persistentVolumeClaim:
        claimName: nexus3-claim
