kind: Service
apiVersion: v1
metadata:
  name: nexus3
  labels: 
    name: nexus3
spec:
  type: NodePort
  ports:
    - name: nexus3-web
      port: 8081
      targetPort: nexus3-web
      nodePort: 8081
    - name: nexus3-https
      port: 8443
      targetPort: nexus3-https
      nodePort: 8443
    - name: nexus3-regist
      port: 8083
      targetPort: nexus3-regist
      nodePort: 8083
    - name: nexus3-push
      port: 5000
      targetPort: nexus3-push
      nodePort: 5000
  selector: 
    name: nexus3         #对应对应的pod/Deployment
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: nexus3-ingress
#spec:
#  rules:
#  - host: nexus.letee.top
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: nexus3-svc
#          servicePort: 8081