kind: Pod
apiVersion: v1
metadata:
  name: nexus3-pod
spec:
  containers:
  - name: nexus3-pod
    image: sonatype/nexus3:3.15.2
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/nexus-data"
    ports:  
    - name: nexus3-web 
      containerPort: 8081 
      hostPort: 8081
      protocol: TCP
    - name: nexus3-https
      containerPort: 443
    - name: nexus3-regist
      containerPort: 8083
    - name: nexus3-push
      containerPort: 5000
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: nexus3-claim