apiVersion: v1
kind: ReplicationController
metadata:
  name: nexus3
  labels:
    name: nexus3
spec:
  replicas: 1
  selector:
    name: nexus3
  template:
    metadata:
      labels: 
        name: nexus3
    spec:
      containers:
      - name: nexus3
        image: sonatype/nexus3:3.15.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: nexus3-web 
          containerPort: 8081
        - name: nexus3-https
          containerPort: 8443
        - name: nexus3-regist
          containerPort: 8083
        - name: nexus3-push
          containerPort: 5000
        env:
        - name: TZ
          value: Asia/Shanghai
        # - name: LAUNCHER_CONF
        #   value: "./conf/jetty.xml ./conf/jetty-requestlog.xml ./conf/jetty-https.xml"
        volumeMounts:
          - name: nfs-pvc
            mountPath: "/nexus-data"
      restartPolicy: "Always"
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: nexus3-claim                 
# docker pull alpine:3.5
# docker tag alpine:3.5 192.168.1.4:5000/alpine:3.5
# docker push 192.168.1.4:5000/alpine:3.5