kind: Service
apiVersion: v1
metadata:
  name: nexus3-svc
  labels: 
    name: nexus3-svc
spec:
  selector: 
    app: nexus3-pod         #对应对应的pod/Deployment
  type: NodePort
  ports:
    - name: nexus3-web
      port: 8081
      targetPort: 8081
      nodePort: 8081
    - name: nexus3-https
      port: 8443
      targetPort: 8443
      nodePort: 8443
    - name: nexus3-docker-regist
      port: 8083
      targetPort: 8083
      nodePort: 8083
    - name: nexus3-docker-push
      port: 5000
      targetPort: 5000
      nodePort: 5000
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: nexus3-ingress
#spec:
#  rules:
#  - host: nexus.letee.top
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: nexus3-svc
#          servicePort: 8081