apiVersion: v1
kind: Service
metadata:
  name: codepush-svc
  labels: 
    name: codepush-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: codepush
    nodePort: 30080
  selector:
    name: codepush-pod