apiVersion: v1
kind: Service
metadata:
  name: codepush-svc
  labels: 
    name: codepush-svc
spec:
  type: NodePort
  ports:
  - name: cpdownload
    port: 3001
    targetPort: cpdownload
    nodePort: 3001
  - name: cpweb
    port: 3002
    targetPort: cpweb
    nodePort: 3002
  - name: codepushlogin
    port: 3200
    targetPort: codepushlogin
    nodePort: 3200
  selector:
    name: codepush-pod
