apiVersion: v1
kind: ReplicationController
metadata:
  name: codepush-rc
  labels:
    name: codepush-rc
spec:
  replicas: 1
  selector:
    name: codepush-pod
  template:
    metadata:
      labels: 
        name: codepush-pod
    spec:
      containers:
      - name: codepush
        image: 192.168.1.4:5000/min_codepush:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 3001
          name: cpdownload
        - containerPort: 3002
          name: cpweb
        volumeMounts:
          - name: codepush-data
            mountPath: "/data"
      restartPolicy: "Always"
      volumes:
        - name: codepush-data
          persistentVolumeClaim:
            claimName: codepush-claim