apiVersion: v1
kind: ReplicationController
metadata:
  name: codepush-rc
  labels:
    name: codepush-rc
spec:
  replicas: 1
  selector:
    name: codepush-pod
  template:
    metadata:
      labels: 
        name: codepush-pod
    spec:
      containers:
      - name: codepush
        image: 192.168.1.4:5000/min_codepush:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 3200
          name: codepushlogin
        volumeMounts:
          - name: codepush-data
            mountPath: "/data"
          - name: codepush-config
            subPath: "config.js"
            mountPath: "/config.js"
          - name: codepush-process
            subPath: "process.json"
            mountPath: "/process.json"
      restartPolicy: "Always"
      volumes:
        - name: codepush-data
          persistentVolumeClaim:
            claimName: codepush-claim
        - name: codepush-config
          configMap: 
            name: codepush-config
            items:
            - key: config.js
              path: config.js
        - name: codepush-process
          configMap:
            name: codepush-config
            items:
            - key: process.json
              path: process.json
