apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: skywalking-oap-rc
  namespace: kube-system
spec:
  serviceName: "skywalking-oap-pod"
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-oap-pod
  template:
    metadata:
      labels: 
        app: skywalking-oap-pod
    spec:
      containers:
      - name: skywalking-oap
        image: 192.168.1.4:5000/apache/skywalking-oap-server:7.0.0-es7 # 拉取得最好是自己的nexus 快
        imagePullPolicy: IfNotPresent
        # livenessProbe:  # 用于判断容器是否存活
        #   tcpSocket:    # 三种探针http(200/3xx) tcp exec(0)
        #     port: 12800
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe: # 用于判断是否启动完成
        #   tcpSocket:
        #     port: 12800
        #   initialDelaySeconds: 15
        #   periodSeconds: 20        
        resources:   #QOS级别Burstable  BestEffort < Burstable < Guaranteed
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 2000m
            memory: 1Gi        
        env:  # 暂时用环境变量配置
        - name: TZ
          value: Asia/Shanghai

        - name: JAVA_OPTS
          value: "-Xmx2g -Xms2g"
        - name: SW_CLUSTER
          value: standalone
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: SW_STORAGE
          value: elasticsearch7
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: 192.168.1.4:9201
        - name: SW_NAMESPACE  # 访问es获取集群名字
          value: docker-cluster
        # - name: SW_ES_USER
        #   value: elastic
        # - name: SW_ES_PASSWORD
        #   value: XXXXXX

        ports:
        - name: skywalking-rest
          containerPort: 12800
        - name: skywalking-grpc
          containerPort: 11800
      restartPolicy: "Always"