apiVersion: v1
kind: ReplicationController
metadata:
  name: skywalking-ui-rc
  namespace: kube-system
  labels:
    name: skywalking-ui-rc
spec:
  replicas: 1
  selector:
    name: skywalking-ui-pod
  template:
    metadata:
      labels: 
        name: skywalking-ui-pod
    spec:
      containers:
      - name: skywalking-ui
        image: 192.168.1.4:5000/apache/skywalking-ui:7.0.0
        imagePullPolicy: IfNotPresent
        resources:   #QOS级别Burstable  BestEffort < Burstable < Guaranteed
          requests:
            memory: 512Mi
          limits:
            memory: 512Mi
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: SW_OAP_ADDRESS
          value: 192.168.1.4:12800     
        ports:
        - name: skywalking-ui 
          containerPort: 8080              
      restartPolicy: "Always"