kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: skywalking
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: skywalking-agent
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
