apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-rc
  labels:
    name: mysql-rc
spec:
  replicas: 1
  selector:
    name: mysql-pod
  template:
    metadata:
      labels: 
        name: mysql-pod
    spec:
      tolerations: #快速驱离pod到其他节点
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      containers:
      - name: mysql
        image: mysql:5.6.45
        imagePullPolicy: IfNotPresent
        args: 
          - "--character-set-server=utf8mb4"
          - "--collation-server=utf8mb4_unicode_ci"   
          #Remove after first replicas=1 create 
          #- "--wsrep-new-cluster"
          #这里在执行的时候代表会创建新集
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Hgxxmm.@6"
        volumeMounts:
          - name: mysql-data
            mountPath: "/var/lib/mysql"
          - name: mysql-conf 
            mountPath: "/etc/mysql/conf.d"
      restartPolicy: "Always"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-claim
        - name: mysql-conf
          configMap: 
            name: mysql-conf
            items:
            - key: our-mysql.cnf
              path: our-mysql.cnf    
