apiVersion: v1
kind: ReplicationController
metadata:
  name: mysqld-exp-rc
spec:
  replicas: 1
  selector:
    name: mysqld-exp-pod
  template:
    metadata:
      labels: 
        name: mysqld-exp-pod
    spec:
      containers:
      - name: mysqld-exp
        image: prom/prometheus:v2.17.2  # https://hub.docker.com/_/zookeeper
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 9090
          name: mysqld-exp
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prom-conf
          subPath: prometheus.yml
      restartPolicy: "Always"
      volumes:
      - name: prom-conf
        configMap:
          name: prom-conf