apiVersion: v1
kind: ReplicationController
metadata:
  name: mysqld-exp-rc
spec:
  replicas: 1
  selector:
    name: mysqld-exp-pod
  template:
    metadata:
      labels: 
        name: mysqld-exp-pod
    spec:
      containers:
      - name: mysqld-exp
        image: 192.168.1.4:5000/liangguohun/mysqld_exporter:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: DATA_SOURCE_NAME
          value: "exporter:xxmm.@6@(192.168.1.4:31306)/"         
        ports:
        - containerPort: 9104
          name: mysqld-exp
      restartPolicy: "Always"