apiVersion: v1
kind: ReplicationController
metadata:
  name: yapi-rc
  labels:
    name: yapi-rc
spec:
  replicas: 1
  selector:
    name: yapi-pod
  template:
    metadata:
      labels: 
        name: yapi-pod
    spec:
      containers:
      - name: yapi
        image: 192.168.1.4:5000/yapi:yapi-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 3000
          name: yapi
        volumeMounts:
        - name: yapi-claim  # 挂载的是源码配置及lock锁定初始化的文件，可以随时修改
          mountPath: /yapi
      restartPolicy: "Always"
      volumes:
      - name: yapi-claim
        persistentVolumeClaim:
          claimName: yapi-claim