apiVersion: v1
kind: Service
metadata:
  name: yapi-svc
  labels: 
    name: yapi-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: yapi
    nodePort: 30080
  selector:
    name: yapi-pod