apiVersion: v1
kind: Service
metadata:
  name: yapi-svc
  labels: 
    name: yapi-svc
spec:
  type: NodePort
  ports:
  - port: 3200
    protocol: TCP
    targetPort: yapi
    nodePort: 3200
  selector:
    name: yapi-pod