apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash-rc
spec:
  replicas: 1
  selector:
    name: logstash-pod
  template:
    metadata:
      labels: 
        name: logstash-pod
    spec:
      containers:
      - name: logstash
        image: logstash:7.6.2  # https://hub.docker.com/_/logstash
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - mountPath: /usr/share/logstash/config/logstash.yml
          name: logstash-conf
          subPath: logstash.yml
        - mountPath: /usr/share/logstash/config/pipelines.yml
          name: logstash-pipelines
          subPath: pipelines.yml
        - mountPath: /usr/share/logstash/pipeline/mysql-log.conf
          name: mysql-log
          subPath: mysql-log.conf
      restartPolicy: "Always"
      volumes:
      - name: logstash-conf
        configMap:
          name: logstash-conf
      - name: logstash-pipelines
        configMap:
          name: logstash-pipelines
      - name: mysql-log 
        configMap:
          name: mysql-log
