apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash-rc
spec:
  replicas: 1
  selector:
    name: logstash-pod
  template:
    metadata:
      labels: 
        name: logstash-pod
    spec:
      containers:
      - name: logstash
        image: logstash:7.6.2  # https://hub.docker.com/_/logstash
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
      restartPolicy: "Always"