apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-rc
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-pod
  template:
    metadata:
      labels: 
        name: mongo-pod
    spec:
      containers:
      - name: mongo
        image: 192.168.1.4:5000/mongo:4.2.0-bionic  #开放了远程密码访问
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "mongoadmin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "xyMm..@hg/0k"
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
          - name: mongo-data
            mountPath: "/data/db"
          - name: mongo-cfg
            mountPath: "/data/configdb"
      restartPolicy: "Always"
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-claim
        - name: mongo-cfg
          persistentVolumeClaim:
            claimName: mongo-cfg